const mongoose=require('mongoose');
const ProSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        unique:true
    },
    category:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true  
    },
    quantity:{
        type:Number,
        required:true  
    },
    features:{
        type:String,
        required:true
    },
    imageURL:{
        type:String,
        required:true,
    }
},{timestamps:true});
module.exports=mongoose.model("product",ProSchema);